const CACHE='wildoku-beta-0.9.18';
const APP_SHELL=[
'./','./index.html','./manifest.webmanifest','./icon-192.png','./icon-512.png','./fox-avatar.png','./version.json',
'./forest-scene-approved.jpg','./tree-stump-approved.png','./boulder-approved.png','./campfire-approved.png','./bench-approved.png','./lantern-approved.png','./flat-rock-approved.png',
'./fox-character.png','./hannah-character.png','./ben-character.png','./clara-character.png','./marcel-character.png','./tom-character.png',
'./lukas-character.png','./tina-character.png','./lena-character.png','./jonas-character.png','./sophie-character.png','./finn-character.png'
];
self.addEventListener('install',event=>{event.waitUntil((async()=>{const cache=await caches.open(CACHE);for(const path of APP_SHELL){try{const req=new Request(path,{cache:'reload'});const res=await fetch(req);if(res&&res.ok)await cache.put(req,res.clone())}catch(e){console.warn('Precache skipped',path,e)}}await self.skipWaiting()})())});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('wildoku-beta-')&&k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim()})())});
self.addEventListener('message',event=>{if(event.data&&event.data.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(url.origin!==self.location.origin)return;if(url.pathname.endsWith('/version.json')){event.respondWith(fetch(req,{cache:'no-store'}).catch(()=>caches.match(req)));return}if(req.mode==='navigate'){event.respondWith((async()=>{try{const fresh=await fetch(req,{cache:'no-store'});if(fresh&&fresh.ok){const c=await caches.open(CACHE);await c.put('./index.html',fresh.clone());return fresh}}catch(e){}const c=await caches.open(CACHE);return (await c.match('./index.html'))||(await c.match('./'))||new Response('Offline',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}})})());return}event.respondWith((async()=>{const c=await caches.open(CACHE);const hit=await c.match(req);if(hit)return hit;try{const fresh=await fetch(req);if(fresh&&fresh.ok)await c.put(req,fresh.clone());return fresh}catch(e){return new Response('',{status:504})}})())});
